# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: funky-select 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "funky-select"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Dan Garland"]
  s.date = "2014-01-19"
  s.description = "A custom drop-down list with styles, used on the SupaDupa project"
  s.email = "dan@dangarland.co.uk"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/assets/images/drop-down-arrow.png",
    "app/assets/images/input-background.gif",
    "app/assets/javascripts/funky-select.js.coffee",
    "app/assets/stylesheets/funky-select.scss",
    "features/funky_select.feature",
    "features/step_definitions/funky_select_steps.rb",
    "features/support/env.rb",
    "funky-select.gemspec",
    "lib/funky-select.rb",
    "lib/funky-select/action_view/helpers/form_builder.rb",
    "test/dummy/README.rdoc",
    "test/dummy/Rakefile",
    "test/dummy/app/assets/javascripts/application.js",
    "test/dummy/app/assets/javascripts/fruits.js",
    "test/dummy/app/assets/stylesheets/application.css",
    "test/dummy/app/assets/stylesheets/fruits.css",
    "test/dummy/app/assets/stylesheets/scaffold.css",
    "test/dummy/app/controllers/application_controller.rb",
    "test/dummy/app/controllers/fruits_controller.rb",
    "test/dummy/app/helpers/application_helper.rb",
    "test/dummy/app/helpers/fruits_helper.rb",
    "test/dummy/app/mailers/.gitkeep",
    "test/dummy/app/models/.gitkeep",
    "test/dummy/app/models/fruit.rb",
    "test/dummy/app/views/fruits/_form.html.erb",
    "test/dummy/app/views/fruits/edit.html.erb",
    "test/dummy/app/views/fruits/index.html.erb",
    "test/dummy/app/views/fruits/new.html.erb",
    "test/dummy/app/views/fruits/show.html.erb",
    "test/dummy/app/views/layouts/application.html.erb",
    "test/dummy/config.ru",
    "test/dummy/config/application.rb",
    "test/dummy/config/boot.rb",
    "test/dummy/config/database.yml",
    "test/dummy/config/environment.rb",
    "test/dummy/config/environments/development.rb",
    "test/dummy/config/environments/production.rb",
    "test/dummy/config/environments/test.rb",
    "test/dummy/config/initializers/backtrace_silencers.rb",
    "test/dummy/config/initializers/inflections.rb",
    "test/dummy/config/initializers/mime_types.rb",
    "test/dummy/config/initializers/secret_token.rb",
    "test/dummy/config/initializers/session_store.rb",
    "test/dummy/config/initializers/wrap_parameters.rb",
    "test/dummy/config/locales/en.yml",
    "test/dummy/config/routes.rb",
    "test/dummy/db/development.sqlite3",
    "test/dummy/db/migrate/20140119124405_create_fruits.rb",
    "test/dummy/db/schema.rb",
    "test/dummy/lib/assets/.gitkeep",
    "test/dummy/log/.gitkeep",
    "test/dummy/public/404.html",
    "test/dummy/public/422.html",
    "test/dummy/public/500.html",
    "test/dummy/public/favicon.ico",
    "test/dummy/script/rails",
    "test/dummy/test/fixtures/fruits.yml",
    "test/dummy/test/functional/fruits_controller_test.rb",
    "test/dummy/test/unit/fruit_test.rb",
    "test/dummy/test/unit/helpers/fruits_helper_test.rb",
    "test/funky-select_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/dmgarland/funky-select"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.1"
  s.summary = "A ul list masquerading as a select box"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 3.2"])
      s.add_runtime_dependency(%q<jquery-rails>, [">= 0"])
      s.add_runtime_dependency(%q<sass-rails>, [">= 0"])
      s.add_runtime_dependency(%q<coffee-rails>, ["= 3.2.2"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.0"])
      s.add_development_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<selenium-webdriver>, [">= 0"])
      s.add_development_dependency(%q<database_cleaner>, [">= 1.2"])
      s.add_development_dependency(%q<pry>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 3.2"])
      s.add_dependency(%q<jquery-rails>, [">= 0"])
      s.add_dependency(%q<sass-rails>, [">= 0"])
      s.add_dependency(%q<coffee-rails>, ["= 3.2.2"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.0"])
      s.add_dependency(%q<cucumber-rails>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<selenium-webdriver>, [">= 0"])
      s.add_dependency(%q<database_cleaner>, [">= 1.2"])
      s.add_dependency(%q<pry>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 3.2"])
    s.add_dependency(%q<jquery-rails>, [">= 0"])
    s.add_dependency(%q<sass-rails>, [">= 0"])
    s.add_dependency(%q<coffee-rails>, ["= 3.2.2"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.0"])
    s.add_dependency(%q<cucumber-rails>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<selenium-webdriver>, [">= 0"])
    s.add_dependency(%q<database_cleaner>, [">= 1.2"])
    s.add_dependency(%q<pry>, [">= 0"])
  end
end

